[General]
capturePopupStyle=compact
openEditor=false
showWelcome=false
soundVolume=50

[capture]
lastRegion="DP-2|820,467,327,163"
selectionGuides=true

[editor]
fillColor=#66c8acd6

[ui]
themesSeeded=true
themesSeededFiles=catppuccin-latte.json, catppuccin-mocha.json, dracula.json, gruvbox.json, nord.json
trayIconPath=:/resources/icons/tray/logo-lens.svg
useSystemDecoration=true
